import type { Metadata } from "next";
import Image from "next/image";

import "./globals.css";
import Link from "next/link";
import Logo from "./components/logo";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const socLinks = [
  { name: "facebook", link: "" },
  { name: "instagram", link: "" },
  { name: "linkedin", link: "" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen flex flex-col justify-between">
        <header className="flex justify-between py-6 px-8">
          <Logo />
          <label className="py-3 px-6 border border-zinc-500 border-opacity-30 rounded-full flex gap-2">
            <Image
              className=""
              width={18}
              height={18}
              src="/icons/search.svg"
              alt="search"
            />
            <input
              className="bg-transparent text-neutral-50 placeholder:text-neutral-50 placeholder:uppercase placeholder:font-medium outline-none"
              type="text"
              placeholder="search"
            />
          </label>
        </header>
        <main>{children}</main>
        <footer className="">
          <div className="flex items-center justify-between py-16 px-16">
            <Logo />
            <p className="font-normal text-base text-neutral-50">Comics</p>
            <div className="flex gap-4">
              {socLinks.map(({ name, link }) => (
                <div className="cursor-pointer" key={name}>
                  <Image
                    className=""
                    width={40}
                    height={40}
                    src={`/icons/${name}.svg`}
                    alt="logo"
                  />
                </div>
              ))}
            </div>
          </div>
          <div className="bg-[#34387F] py-[18px] flex justify-center">
            <a href="" className="text-neutral-50 text-opacity-40">
              Privacy Policy Public Offering Agreement
            </a>
          </div>
        </footer>
      </body>
    </html>
  );
}
